### ISSUE TITLE
The problem relates to the dataset

### ISSUE THREAD

**Issue by tranquangchung** [SIAAAAAA/MMT-PSM#1]
Dear author

First of all, thank you for sharing a useful source code.
The problem "Overlapping Cervical Cell Instance Segmentation" is a domain that I research. And your code can support me a lot in this domain.
If your dataset has not a security policy, could you share it with me that you use in your study?
My email is: bktranquangchung@gmail.com

Looking forward to your reply
Best regards
@SIAAAAAA

**Comment by Amandaynzhou** [comment]
Hi, @tranquangchung,

We are preparing for releasing. But currently, it is not publicly available.

Thanks,
Yanning
