### ISSUE TITLE
a little bug in the code  nms.cu

### ISSUE THREAD

**Issue by jiangyangbo** [SIAAAAAA/MMT-PSM#3]
when compile your project ,  nvcc show that there are some bugs . finally ,  it come outs as a little bug in the  file 'MMT-PSM/maskrcnn_benchmark/csrc/cuda/nms.cu'   ,  there is a  additional word 'v' in the first line , which result  some unknown errors.

**Comment by Amandaynzhou** [comment]
Hi,@jiangyangbo

Yes. Sorry, that there may exist bugs in the folder '/csrc'. 
We compile the code from Detectron-v1(Facebook) and do not rebuild it later. So I suggest that you can find the original one from their repo. I will update them later. Thanks.

Best wishes,
Yanning
